[samba36] samba server build depends on libuuid
02:41:03 In file included from ../lib/addns/dnsrecord.c:24:0:
02:41:03 ../lib/addns/dns.h:53:23: fatal error: uuid/uuid.h: No such
file or directory

Change-Id: I6608b5fa8841747ae49fb2b83ad2cdf984034e5f
Signed-off-by: Matthew McClintock <mmcclint@codeaurora.org>
Reviewed-by: Mathieu Olivari <mathieu@codeaurora.org>